language: python
python:
  - "3.5"
env:
  - DJANGO=1.11.16
install:
  - pip install -q Django==$DJANGO
  - pip install coveralls
script:
  - python manage.py test ilmo_app
script:
  - coverage run --source=your_app manage.py test ilmo_app
after_success:
  - coveralls
